# Generated by Django 5.1.6 on 2025-03-02 18:28

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoVip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Grupo VIP')),
                ('grupo_id', models.CharField(max_length=50, unique=True, verbose_name='ID do Grupo no Telegram')),
                ('token_bot_conversa', models.CharField(max_length=100, verbose_name='Token do Bot de Conversa')),
                ('gateway_pagamento', models.CharField(choices=[('mercadopago', 'Mercado Pago'), ('efi', 'EFI'), ('pushinpay', 'PushinPay')], default='mercadopago', max_length=20, verbose_name='Gateway de Pagamento')),
                ('token_gateway', models.CharField(max_length=255, verbose_name='Token do Gateway')),
                ('mensagem_boas_vindas', models.TextField(verbose_name='Mensagem de Boas-Vindas')),
                ('midia_boas_vindas', models.FileField(blank=True, null=True, upload_to='boas_vindas/', verbose_name='Mídia de Boas-Vindas')),
            ],
            options={
                'verbose_name': 'Grupo VIP',
                'verbose_name_plural': 'Grupos VIP',
            },
        ),
        migrations.CreateModel(
            name='Plano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Plano')),
                ('valor_original', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Original')),
                ('valor_downsell', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor de Downsell')),
                ('valor_remarketing', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor de Remarketing')),
                ('duracao_dias', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(365)], verbose_name='Duração (dias)')),
                ('descricao', models.TextField(verbose_name='Descrição do Plano')),
                ('dias_antecedencia_renovacao', models.JSONField(default=list, help_text='Ex: [5, 1] para 5 e 1 dias antes', verbose_name='Dias Antecedência Renovação')),
                ('mensagem_renovacao', models.TextField(verbose_name='Mensagem de Renovação')),
                ('duracao_downsell', models.PositiveIntegerField(default=3, help_text='Dias após inatividade para enviar downsell', verbose_name='Duração para Downsell (dias)')),
                ('mensagem_downsell', models.TextField(verbose_name='Mensagem de Downsell')),
                ('grupo_vip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planos', to='core.grupovip', verbose_name='Grupo VIP')),
            ],
            options={
                'verbose_name': 'Plano',
                'verbose_name_plural': 'Planos',
                'ordering': ['valor_original'],
            },
        ),
    ]
